[opener]

image = [
    { run = 'viewnior %s', orphan = true, for = "unix" },
]

pdf = [
    { run = 'mupdf %s', orphan = true, for = "unix" },
]

video = [
    { run = 'mpv %s', orphan = true, for = "unix" },
]

browser = [
    { run = 'app.zen_browser.zen %s', orphan = true, for = "unix" },
]

edit = [
    { run = 'nvim %s', block = true, for = "unix" },
]

[open]

prepend_rules = [
    { url = "*.{png,jpg,jpeg,gif,webp,bmp}", use = "image" },
    { url = "*.pdf", use = "pdf" },
    { url = "*.{mp4,mkv,webm,avi,mov}", use = "video" },
    { url = "*.html", use = "browser" },
    { url = "*.{md,txt}", use = "edit" },
]
