#!/usr/bin/env python3

from pathlib import Path
import json


BASE = Path.home() / ".config/walltheme"

THEME_FILE = BASE / "current.json"
OUTPUT = BASE / "generated" / "waybar.css"


def main():

    with open(THEME_FILE) as f:
        theme = json.load(f)

    css = f"""/*
 * =====================================================
 * WALLTHEME — GENERATED WAYBAR PALETTE
 *
 * DO NOT EDIT THIS FILE.
 *
 * Source:
 * {theme["wallpaper"]}
 * =====================================================
 */

@define-color background {theme["background"]};
@define-color surface {theme["surface"]};
@define-color surface_alt {theme["surface_alt"]};

@define-color foreground {theme["foreground"]};
@define-color muted {theme["muted"]};

@define-color border {theme["border"]};

@define-color accent {theme["accent"]};
@define-color accent_hover {theme["accent_hover"]};
@define-color accent_active {theme["accent_active"]};

@define-color accent_secondary {theme["accent_secondary"]};

@define-color selection {theme["selection"]};

@define-color warning {theme["warning"]};
@define-color error {theme["error"]};
@define-color success {theme["success"]};

@define-color black {theme["black"]};
@define-color white {theme["white"]};
"""

    OUTPUT.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    OUTPUT.write_text(css)

    print(f"Generated → {OUTPUT}")


if __name__ == "__main__":
    main()
