#!/usr/bin/env python3

from pathlib import Path
import json
import os


# =========================================================
# CONFIGURATION
# =========================================================

BASE = Path.home() / ".config" / "walltheme"

THEME_FILE = BASE / "current.json"

OUTPUT_DIR = Path.home() / ".config" / "btop" / "themes"

OUTPUT = OUTPUT_DIR / "walltheme.theme"


# =========================================================
# COLOR UTILITIES
# =========================================================

def hex_to_rgb(value):
    value = value.lstrip("#")

    return tuple(
        int(value[i:i + 2], 16)
        for i in (0, 2, 4)
    )


def rgb_to_hex(rgb):
    return "#{:02x}{:02x}{:02x}".format(*rgb)


def mix(c1, c2, amount):
    return tuple(
        round(
            c1[i] * (1 - amount) +
            c2[i] * amount
        )
        for i in range(3)
    )


def relative_luminance(rgb):
    values = []

    for value in rgb:
        channel = value / 255

        if channel <= 0.03928:
            channel /= 12.92
        else:
            channel = (
                (channel + 0.055) / 1.055
            ) ** 2.4

        values.append(channel)

    r, g, b = values

    return (
        0.2126 * r +
        0.7152 * g +
        0.0722 * b
    )


def contrast_ratio(c1, c2):
    l1 = relative_luminance(c1)
    l2 = relative_luminance(c2)

    lighter = max(l1, l2)
    darker = min(l1, l2)

    return (
        (lighter + 0.05) /
        (darker + 0.05)
    )


def best_text_color(background, candidates):
    return max(
        candidates,
        key=lambda color: contrast_ratio(
            color,
            background
        )
    )


# =========================================================
# TONAL RAMPS
#
# Btop supports three stops per gradient:
#
#   start → mid → end
#
# Instead of repeating nearly identical wallpaper colors,
# generate a darker tone and a lighter tint around each
# wallpaper-derived accent.
# =========================================================

def tonal_ramp(
    rgb,
    background,
    foreground,
    dark_mix=0.55,
    bright_mix=0.35,
):
    dark = mix(
        rgb,
        background,
        dark_mix
    )

    bright = mix(
        rgb,
        foreground,
        bright_mix
    )

    return (
        dark,
        rgb,
        bright,
    )


# =========================================================
# LOAD WALLTHEME
# =========================================================

with open(THEME_FILE) as file:
    theme = json.load(file)


# =========================================================
# CORE COLORS
# =========================================================

background = hex_to_rgb(
    theme["background"]
)

surface = hex_to_rgb(
    theme["surface"]
)

surface_alt = hex_to_rgb(
    theme["surface_alt"]
)

foreground = hex_to_rgb(
    theme["foreground"]
)

muted = hex_to_rgb(
    theme["muted"]
)

accent = hex_to_rgb(
    theme["accent"]
)

accent_hover = hex_to_rgb(
    theme["accent_hover"]
)

accent_secondary = hex_to_rgb(
    theme["accent_secondary"]
)

accent_tertiary = hex_to_rgb(
    theme["accent_tertiary"]
)

accent_surface = hex_to_rgb(
    theme["accent_surface"]
)


# =========================================================
# GENERATE TONAL PALETTES
# =========================================================

accent_ramp = tonal_ramp(
    accent,
    background,
    foreground
)

secondary_ramp = tonal_ramp(
    accent_secondary,
    background,
    foreground
)

tertiary_ramp = tonal_ramp(
    accent_tertiary,
    background,
    foreground
)

hover_ramp = tonal_ramp(
    accent_hover,
    background,
    foreground,
    dark_mix=0.45,
    bright_mix=0.45,
)


accent_dark, accent_mid, accent_bright = accent_ramp

secondary_dark, secondary_mid, secondary_bright = (
    secondary_ramp
)

tertiary_dark, tertiary_mid, tertiary_bright = (
    tertiary_ramp
)

hover_dark, hover_mid, hover_bright = hover_ramp


# =========================================================
# SELECTED PROCESS ROW
# =========================================================

selected_foreground = best_text_color(
    accent_surface,
    (
        background,
        foreground,
        muted,
    )
)


# =========================================================
# BTOP THEME
#
# Different widgets intentionally use different combinations
# of the wallpaper-derived tonal ramps. This gives the UI
# richer gradients without introducing unrelated colors.
# =========================================================

config = f"""# =====================================================
# WALLTHEME — GENERATED BTOP THEME
#
# DO NOT EDIT THIS FILE.
#
# Source wallpaper:
# {theme["wallpaper"]}
#
# Btop supports three gradient stops:
# start → mid → end
#
# Each stop below is derived from the Walltheme palette.
# =====================================================


# =====================================================
# CORE
# =====================================================

# Preserve terminal transparency.
theme[main_bg]=""

theme[main_fg]="{rgb_to_hex(foreground)}"

theme[title]="{rgb_to_hex(accent)}"

theme[hi_fg]="{rgb_to_hex(accent_hover)}"


# =====================================================
# PROCESS SELECTION
# =====================================================

theme[selected_bg]="{rgb_to_hex(accent_surface)}"

theme[selected_fg]="{rgb_to_hex(selected_foreground)}"

theme[inactive_fg]="{rgb_to_hex(muted)}"

theme[proc_misc]="{rgb_to_hex(secondary_mid)}"


# =====================================================
# BOX OUTLINES
# =====================================================

theme[cpu_box]="{rgb_to_hex(accent_mid)}"

theme[mem_box]="{rgb_to_hex(secondary_mid)}"

theme[net_box]="{rgb_to_hex(tertiary_mid)}"

theme[proc_box]="{rgb_to_hex(accent_bright)}"

theme[div_line]="{rgb_to_hex(accent_surface)}"


# =====================================================
# TEMPERATURE
# =====================================================

theme[temp_start]="{rgb_to_hex(secondary_dark)}"
theme[temp_mid]="{rgb_to_hex(accent_mid)}"
theme[temp_end]="{rgb_to_hex(tertiary_bright)}"


# =====================================================
# CPU
# =====================================================

theme[cpu_start]="{rgb_to_hex(accent_dark)}"
theme[cpu_mid]="{rgb_to_hex(accent_mid)}"
theme[cpu_end]="{rgb_to_hex(accent_bright)}"


# =====================================================
# MEMORY / DISK
# =====================================================

theme[free_start]="{rgb_to_hex(secondary_dark)}"
theme[free_mid]="{rgb_to_hex(secondary_mid)}"
theme[free_end]="{rgb_to_hex(accent_bright)}"

theme[cached_start]="{rgb_to_hex(tertiary_dark)}"
theme[cached_mid]="{rgb_to_hex(tertiary_mid)}"
theme[cached_end]="{rgb_to_hex(secondary_bright)}"

theme[available_start]="{rgb_to_hex(hover_dark)}"
theme[available_mid]="{rgb_to_hex(hover_mid)}"
theme[available_end]="{rgb_to_hex(secondary_bright)}"

theme[used_start]="{rgb_to_hex(accent_dark)}"
theme[used_mid]="{rgb_to_hex(accent_mid)}"
theme[used_end]="{rgb_to_hex(hover_bright)}"


# =====================================================
# NETWORK
# =====================================================

theme[download_start]="{rgb_to_hex(tertiary_dark)}"
theme[download_mid]="{rgb_to_hex(accent_mid)}"
theme[download_end]="{rgb_to_hex(secondary_bright)}"

theme[upload_start]="{rgb_to_hex(secondary_dark)}"
theme[upload_mid]="{rgb_to_hex(tertiary_mid)}"
theme[upload_end]="{rgb_to_hex(accent_bright)}"
"""


# =========================================================
# WRITE ATOMICALLY
# =========================================================

OUTPUT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

TEMP = OUTPUT.with_suffix(".theme.tmp")

TEMP.write_text(
    config,
    encoding="utf-8"
)

os.chmod(
    TEMP,
    0o644
)

os.replace(
    TEMP,
    OUTPUT
)

print(f"Generated → {OUTPUT}")
