#!/usr/bin/env python3

from pathlib import Path
import json


BASE = Path.home() / ".config" / "walltheme"

THEME_FILE = BASE / "current.json"
OUTPUT = BASE / "generated" / "hyprland.conf"


def hex_to_hypr(hex_color):
    """
    Convert #RRGGBB into Hyprland's rgb(RRGGBB) format.
    """

    return hex_color.lstrip("#")


def main():

    with open(THEME_FILE) as f:
        theme = json.load(f)

    background = hex_to_hypr(
        theme["background"]
    )

    surface = hex_to_hypr(
        theme["surface"]
    )

    surface_alt = hex_to_hypr(
        theme["surface_alt"]
    )

    foreground = hex_to_hypr(
        theme["foreground"]
    )

    muted = hex_to_hypr(
        theme["muted"]
    )

    accent = hex_to_hypr(
        theme["accent"]
    )

    accent_hover = hex_to_hypr(
        theme["accent_hover"]
    )

    accent_active = hex_to_hypr(
        theme["accent_active"]
    )

    accent_surface = hex_to_hypr(
        theme["accent_surface"]
    )

    accent_secondary = hex_to_hypr(
        theme["accent_secondary"]
    )

    accent_tertiary = hex_to_hypr(
        theme["accent_tertiary"]
    )

    border = hex_to_hypr(
        theme["border"]
    )

    selection = hex_to_hypr(
        theme["selection"]
    )

    warning = hex_to_hypr(
        theme["warning"]
    )

    error = hex_to_hypr(
        theme["error"]
    )

    success = hex_to_hypr(
        theme["success"]
    )

    config = f"""# =====================================================
# WALLTHEME — GENERATED HYPRLAND THEME
#
# DO NOT EDIT THIS FILE.
#
# Source wallpaper:
# {theme["wallpaper"]}
# =====================================================


# =====================================================
# WALLTHEME COLOR VARIABLES
# =====================================================

$walltheme_background = rgb({background})
$walltheme_surface = rgb({surface})
$walltheme_surface_alt = rgb({surface_alt})

$walltheme_foreground = rgb({foreground})
$walltheme_muted = rgb({muted})

$walltheme_accent = rgb({accent})
$walltheme_accent_hover = rgb({accent_hover})
$walltheme_accent_active = rgb({accent_active})

$walltheme_accent_surface = rgb({accent_surface})
$walltheme_accent_secondary = rgb({accent_secondary})
$walltheme_accent_tertiary = rgb({accent_tertiary})

$walltheme_border = rgb({border})
$walltheme_selection = rgb({selection})

$walltheme_warning = rgb({warning})
$walltheme_error = rgb({error})
$walltheme_success = rgb({success})


# =====================================================
# ACTIVE / INACTIVE WINDOW BORDERS
# =====================================================

$walltheme_active_border = $walltheme_accent_surface
$walltheme_inactive_border = $walltheme_border


# =====================================================
# SPECIAL / URGENT
# =====================================================

$walltheme_urgent = $walltheme_error
"""

    OUTPUT.parent.mkdir(
        parents=True,
        exist_ok=True
    )

    OUTPUT.write_text(config)

    print(
        f"Generated → {OUTPUT}"
    )


if __name__ == "__main__":
    main()
