#!/usr/bin/env python3

from pathlib import Path
import json


# =========================================================
# CONFIGURATION
# =========================================================

BASE = Path.home() / ".config" / "walltheme"

THEME_FILE = BASE / "current.json"

OUTPUT = (
    Path.home()
    / ".config"
    / "hypr"
    / "hyprlock.conf"
)


# =========================================================
# COLOR HELPERS
# =========================================================

def hex_to_rgb(value):
    value = value.lstrip("#")

    return (
        int(value[0:2], 16),
        int(value[2:4], 16),
        int(value[4:6], 16),
    )


def rgb_color(value):
    r, g, b = hex_to_rgb(value)

    return f"rgb({r}, {g}, {b})"


def rgba_color(value, alpha):
    r, g, b = hex_to_rgb(value)

    return f"rgba({r}, {g}, {b}, {alpha})"


# =========================================================
# LOAD WALLTHEME
# =========================================================

with open(THEME_FILE, "r") as file:
    theme = json.load(file)


# =========================================================
# WALLPAPER
# =========================================================

wallpaper = theme["wallpaper"]


# =========================================================
# COLORS
# =========================================================

surface = theme["surface"]

foreground = theme["foreground"]

muted = theme["muted"]

accent = theme["accent"]

accent_surface = theme["accent_surface"]

error = theme["error"]


# =========================================================
# GENERATE HYPRLOCK CONFIG
# =========================================================

config = f"""# =====================================================
# WALLTHEME — GENERATED HYPRLOCK CONFIG
#
# DO NOT EDIT THIS FILE.
#
# Current wallpaper is managed through:
# ~/Wall/hyprlock-wallpaper.png
#
# Generated from:
# ~/.config/walltheme/current.json
# =====================================================


# =====================================================
# BACKGROUND
# =====================================================

background {{
    monitor =
    path = ~/Wall/hyprlock-wallpaper.png

    blur_passes = 2
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}}


# =====================================================
# INPUT FIELD
# =====================================================

input-field {{
    monitor =

    size = 250, 60

    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true

    outer_color = {rgba_color(accent_surface, "1.0")}
    inner_color = {rgba_color(surface, "0.82")}

    font_color = {rgb_color(foreground)}

    rounding = -1

    check_color = {rgb_color(accent)}
    fail_color = {rgb_color(error)}

    placeholder_text = Input Password...

    position = 0, -150
    halign = center
    valign = center
}}


# =====================================================
# DATE
# =====================================================

label {{
    monitor =

    text = cmd[update:1000] echo "$(date +"%A, %B %d")"

    color = {rgba_color(muted, "0.75")}

    font_size = 22
    font_family = JetBrains Mono

    position = 0, 150
    halign = center
    valign = center
}}


# =====================================================
# TIME
# =====================================================

label {{
    monitor =

    text = cmd[update:1000] echo "$(date +"%-I:%M")"

    color = {rgba_color(foreground, "0.9")}

    font_size = 90
    font_family = JetBrains Mono

    position = 0, 50
    halign = center
    valign = center
}}
"""


# =========================================================
# WRITE CONFIG
# =========================================================

OUTPUT.parent.mkdir(
    parents=True,
    exist_ok=True
)

OUTPUT.write_text(config)

print(f"Generated → {OUTPUT}")
