-- Settings previously generated by HyprMod

hl.config({
    general = {
        snap = {
            enabled = false,
        },
    },

    gestures = {
        workspace_swipe_forever = 1,
    },

    ecosystem = {
        no_update_news = true,
    },
})
